// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_gag4ROMy5qBpCQzVM7z0HdX3O1mZKSs',
    appId: '1:453197713992:web:afaa9d425abaf65048fe7d',
    messagingSenderId: '453197713992',
    projectId: 'business-011',
    authDomain: 'business-011.firebaseapp.com',
    storageBucket: 'business-011.appspot.com',
    measurementId: 'G-23RVPPXEZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-1poQcvKCs4moLxplYp6dlRL6uwtK_mA',
    appId: '1:453197713992:android:229976b4b167fefe48fe7d',
    messagingSenderId: '453197713992',
    projectId: 'business-011',
    storageBucket: 'business-011.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp7I_EOxI-MYIIGx79xGVLsd4ekFtaY2E',
    appId: '1:453197713992:ios:9040b68e32ad38ff48fe7d',
    messagingSenderId: '453197713992',
    projectId: 'business-011',
    storageBucket: 'business-011.appspot.com',
    iosClientId: '453197713992-4kpo22dfd8ei12g32p9ai65oc1c315gg.apps.googleusercontent.com',
    iosBundleId: 'com.example.business',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp7I_EOxI-MYIIGx79xGVLsd4ekFtaY2E',
    appId: '1:453197713992:ios:eabd0988dff9bff448fe7d',
    messagingSenderId: '453197713992',
    projectId: 'business-011',
    storageBucket: 'business-011.appspot.com',
    iosClientId: '453197713992-6j66tgbik22u8mgoekkd0vseuhks2jc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.business.RunnerTests',
  );
}
